language: rust
sudo: required
os:
    - linux
dist: trusty

services:
    - docker

rust:
    - stable
    - nightly
    - 1.16.0

cache:
    directories:
        - target/debug/deps
        - target/debug/build

script:
    - cargo build --verbose
    - cargo test --verbose --no-run

# Coverage report
# Upload docs
after_success:
    - |
        if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" ]]; then
            sudo docker pull ragnaroek/kcov_head:latest &&
            docker images &&
            docker run --security-opt seccomp=unconfined -v $(pwd):/source ragnaroek/kcov_head:latest --exclude-pattern=/.cargo,/usr/lib --verify target/cov target/debug/automaton-* &&
            bash <(curl -s https://codecov.io/bash) &&
            echo "Uploaded code coverage"
        fi
    - |
        if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" && "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" == "master" ]]; then
            cargo doc --no-deps &&
            echo "<meta http-equiv=refresh content=0;url=automaton/index.html>" > target/doc/index.html &&
            git clone https://github.com/davisp/ghp-import.git &&
            ./ghp-import/ghp_import.py -n -p -f -m "Documentation upload" -r https://"$GH_TOKEN"@github.com/"$TRAVIS_REPO_SLUG.git" target/doc &&
            echo "Uploaded documentation"
        fi
