language: rust
sudo: true
os:
    - linux
dist: trusty

rust:
    - stable
    - nightly
    - 1.16.0

cache:
    apt: true
    directories:
        - target/debug/deps
        - target/debug/build

addons:
    apt:
        packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - gcc
            - binutils-dev

# Coverage report
# Upload docs
after_success:
    - |
        if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" ]]; then
            sudo add-apt-repository -y ppa:kubuntu-ppa/backports &&
            sudo apt-get update &&
            sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev libiberty-dev &&
            wget https://github.com/SimonKagstrom/kcov/archive/v33.tar.gz &&
            tar xzf v33.tar.gz && mkdir kcov-33/build && cd kcov-33/build && cmake .. && make &&
            sudo make install && cd ../.. &&
            kcov --verify --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov $(find target/debug -maxdepth 1 -executable -name automaton-\*)
        fi
    - |
        if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" && "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" == "master" ]]; then
            cargo doc --no-deps &&
            echo "<meta http-equiv=refresh content=0;url=automaton/index.html>" > target/doc/index.html &&
            git clone https://github.com/davisp/ghp-import.git &&
            ./ghp-import/ghp_import.py -n -p -f -m "Documentation upload" -r https://"$GH_TOKEN"@github.com/"$TRAVIS_REPO_SLUG.git" target/doc &&
            echo "Uploaded documentation"
        fi
