language: rust
cache: cargo
dist: trusty
os:
    - linux

# Run builds for all the supported trains
rust:
    - nightly
    - stable
    - 1.16.0

sudo: true

before_install:
  - sudo apt-get update

addons:
    apt:
        packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - gcc
            - binutils-dev
            - libbfd-dev

script:
    - cargo build
    - cargo test

# Coverage report
# Upload docs
after_success:
    - |
        if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" ]]; then
            sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev &&
            wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
            tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make &&
            sudo make install && cd ../.. &&
            kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/automaton-* &&
            echo "Uploaded code coverage"
        fi
    - |
        if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" && "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" == "master" ]]; then
            cargo doc &&
            echo "<meta http-equiv=refresh content=0;url=automaton/index.html>" > target/doc/index.html &&
            git clone https://github.com/davisp/ghp-import.git &&
            ./ghp-import/ghp_import.py -n -p -f -m "Documentation upload" -r https://"$GH_TOKEN"@github.com/"$TRAVIS_REPO_SLUG.git" target/doc &&
            echo "Uploaded documentation"
        fi
